### ISSUE TITLE
OF 0.9.0 compile errors

### ISSUE THREAD

**Issue by antimodular** [tiagosr/ofxShadertoy#1]
Hi there.

I am trying to get your addon to run on my MBP with NVIDIA GeForce GT 750M 2048 MB under OS X 10.10

Here is a list of errors i have encountered:

compiling your example gives me this:
`Field type 'ofxShadertoy' is an abstract class`

so i made these changes changes:
command out 
`//ofSetCurrentRenderer(ofGLProgrammableRenderer::TYPE);`

```
//ofxShadertoy shader toy; 
ofxShadertoy *shadertoy;
```

and 

```
//shadertoy.load("shaders/raymarch.frag");
shadertoy->load("shaders/raymarch.frag");
etc
```

which removed all ofxShaderToy related errors.
But in ofxFPSControls i had to command the following calls since these functions seem not to exist in my version of OF:

```
//    ofSetCursorPosition(ofGetWindowWidth()/2, ofGetWindowHeight()/2);
//    ofGrabCursor();
//    ofReleaseCursor();
//    ofSetCursorPosition(center.x, center.y);
```

then the app compiled but crashed and gave me these error messages:

```
[ error ] ofShader: setupShaderFromSource(): GL_VERTEX_SHADER shader failed to compile
[ error ] ofShader: GL_VERTEX_SHADER shader reports:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:2: 'precision' : syntax error: syntax error

[ error ] ofShader: GL_VERTEX_SHADER, offending line 1 :
        1   #version 330
        2   precision mediump float;uniform mat4 modelViewProjectionMatrix;uniform mat4 tCameraMatrix;in vec4 position;void main(){    gl_Position = modelViewProjectionMatrix * position;}
        3   

[ error ] ofShader: setupShaderFromSource(): GL_FRAGMENT_SHADER shader failed to compile
[ error ] ofShader: GL_FRAGMENT_SHADER shader reports:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:2: 'precision' : syntax error: syntax error

[ error ] ofShader: GL_FRAGMENT_SHADER, offending line 1 :
        1   #version 330
        2   precision mediump float;
        3   uniform vec3      iResolution;

[ error ] shader: error loading shader
```

not sure if my GPU is not compatible since  "version '330' is not supported"

thx

**Comment by tiagosr** [comment]
hi @antimodular, unfortunately ofxShadertoy is not yet compatible with oF 0.9.0 - there were some changes on ofBaseDraws that break the class, hence the "Field type 'ofxShadertoy' is an abstract class".
could you try it with oF 0.8.4 for now? it shouldn't need any modifications to work.

**Comment by tiagosr** [comment]
@antimodular I intend to update the addon to support 0.9.0 this weekend, though.
please notice that for ofxFPSControls to work there are some replacement files for oF 0.8.4, to be able to grab the cursor

**Comment by antimodular** [comment]
that sounds great. i will wait for the update.

thanks a lot.

**Comment by tiagosr** [comment]
Just updated the addon, it now compiles clean on oF 0.9.2
I've added a sample for setting up a renderer without the need for the ofxFPSControls addon - I'll update that later.
