### ISSUE TITLE
textures, iChannel, iMouse

### ISSUE THREAD

**Issue by antimodular** [tiagosr/ofxShadertoy#2]
Thanks so much for making the update to OF 0.9.0

Your example and some other shaders work now :)

Do you have more information on how to make it work with an underlying texture and what is the iChannel stuff?
I tried to load in a texture but the shader did not like what i did.

```
    ofImage img;
    img.load("fondo.jpg");
    nifty_texture.loadData(img.getPixels());
   shadertoy.setTexture(0, nifty_texture);
```

here are 2 water ripple shaders i am trying to get working:
https://www.shadertoy.com/view/ldB3Wd
https://www.shadertoy.com/view/4djGzz

I am hoping to find shader code that i can change to give me more control over frequency, amplitude and propagation speed of interfering water ripples. Any pointers?

Thanks.

**Comment by antimodular** [comment]
here is the error code for https://www.shadertoy.com/view/4djGzz

```
[ error ] ofShader: setupShaderFromSource(): GL_FRAGMENT_SHADER shader failed to compile
[ error ] ofShader: GL_FRAGMENT_SHADER shader reports:
ERROR: 0:56: Invalid call of undeclared identifier 'texture2D'

[ error ] ofShader: GL_FRAGMENT_SHADER, offending line 56 :
       54       vec2 uvn = 2.0*uv - vec2(1.0);
       55       uv += normal(uvn, iGlobalTime);
       56       fragColor = texture2D(iChannel0, vec2(1.0-uv.x, uv.y));
       57   }
       58   out vec4 FragColor;void main( void ){vec4 color = vec4(0.0,0.0,0.0,1.0);mainImage( color, gl_FragCoord.xy );color.w = 1.0;FragColor = color;}

[ error ] shader: error loading shader
```

**Comment by tiagosr** [comment]
I've updated the addon once again - there are some changes between desktop GLSL and WebGL GLSL that I was not aware of. I updated it with another sample, too - please note the texture setup there, it's crucial to make textures work right.
