### ISSUE TITLE
ofSetCurrentRenderer is depricated

### ISSUE THREAD

**Issue by Vamoss** [tiagosr/ofxShadertoy#3]
Where:
https://github.com/tiagosr/ofxShadertoy/blob/master/raymarcherExample/src/main.cpp#L5

Solution:
https://forum.openframeworks.cc/t/ofsetcurrentrenderer-in-0-9-0/21304

**Comment by tiagosr** [comment]
fixed in https://github.com/tiagosr/ofxShadertoy/commit/37a6cd758d8ada52344bb2c6119b521f92322ec4
